version: '3.8'

services:
    discord:
        build:
            context: ./discord
        container_name: discord
        networks:
          - network
        environment:
          - RABBITMQ_HOST=rabbitmq
        restart: 'always'
        
    manager:
        build:
          context: ./manager
        container_name: manager
        environment:
          - RABBITMQ_HOST=rabbitmq
        networks: 
          - network
        #network_mode: "default"
        restart: 'always'

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports:
          # The standard AMQP protocol port
          - '5672:5672'
          # HTTP management UI
          - '15672:15672'
        networks: 
          - network
        restart: 'always'

networks:
  network: {}