version: '3.6'
services:
  database:
    image: mariadb:10.1.48
    ports:
      - "13306:3306"
    container_name: database
    network_mode: "default"
    environment:
        MYSQL_ROOT_PASSWORD: "pass"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - ./local_db:/var/lib/mysql
    restart: 'always'
  create_db:
    build:
      context: ./create_db
    network_mode: "default"